### ISSUE TITLE
Master Fire Map 2018 ticket

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapvue#52]
In addition to other specific tickets tagged below:

## Must have

 - [x] #53 Update historical fire layer through 2017 (note: I think they serve this out as a WMS now, so manual updates are likely not necessary, see email from Gary)
 - [x] #54 Update daily data on graph to display 2018 data (and add back in the other high fire years)
 - [x] #62 Add in a tour stop explaining the graph.
 - [x] #55  (Carolyn) On splash screen, change “in context of” to “as related to” -- seems simpler.
 - [x] #55 Also on splash screen, please add to the last sentence: “ maintaining the fire data.”

### Want

 - [x] #56 Change urls to something more descriptive…”map 5” just doesn’t do it for me! Maybe “wildfire”
 - [ ] #57 The app has been incorrect since the 2017-labeled data started displaying 2018 data. Is there a way to avoid this from occurring before we get to updating the application?
 - [x] #58 I really want topo maps. Can we try to add as a background option the first WMS here, USGS Topo Base Map - Primary Tile Cache (Tiled): https://viewer.nationalmap.gov/services/
 - [x] #59 hotspot data (VIIRS would be my top choice but MODIS would be fine too
 - [x] #60 Add the lightning strike layer from AICC (historical from when it was improved, maybe 2012-2017; and then current year updated hourly like the fire perimeters)
https://fire.ak.blm.gov/arcgis/rest/services/MapAndFeatureServices
 - [x] #61 In addition to the historical fire layer, provide an additional layer that  are only the high fire seasons (same ones as in graph: 2004, 2005, 2009, 2010, 2013, 2015), perhaps as unique colors for each year.

#### Other feedback:

Amy:
 * Add the current FMO layer
 * Answer the questions posed!  Or, maybe include a set of FAQs.
 * It would also be nice to show the daily state-wide imagery during the fire season, but not sure what that entails.  I am thinking of the imagery that shows smoke.

Robert
 * On the intro page, along with the other fire links, I recommend including something from the Alaska Fire & Fuels page, perhaps the current FFMC map... https://akff.mesowest.org/map/#/c6570,-15423,5/g1/mc/vffmc/sAK/n/o0.1,1.1,2.1,3.1,8.0.75/zt (the link offered here will include recent lightning, incidents, warnings, and recent viirs and modis fire detections)
