### ISSUE TITLE
Deploy checklist

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/mapvue#90]
Todo for release:

 - [x] Build new production instance of Geoserver on AWS
   - [ ] Install CSS extension
 - [x] Migrate all map data to new instance
   - [x] Create a new workspace for each map, aligned with source code (may need to adjust a few).
  - [x] Generate caches for every layer.
  - [x] Verify sufficient security configuration for Geoserver & its admin interface.
  - [x] Push updated code to production s3 bucket.
